# Transparent Everlife Theme for Alacritty
# https://github.com/Davidrsdiaz/transparent-background-everlife-terminal-cli-theme

[window]
opacity = 0.20
padding = { x = 10, y = 8 }
decorations = "Transparent"
decorations_theme_variant = "Dark"

[font]
normal = { family = "JetBrains Mono", style = "Regular" }
bold = { family = "JetBrains Mono", style = "Bold" }
size = 14.0

[colors]
[colors.primary]
background = "#1e2326"
foreground = "#d3c6aa"

[colors.cursor]
text = "#4c3743"
cursor = "#e69875"

[colors.selection]
text = "#d3c6aa"
background = "#4c3743"

[colors.normal]
black = "#7a8478"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#f2efdf"

[colors.bright]
black = "#a6b0a0"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#fffbef"
