[theme]
name = "everlife"

[theme.colors]
foreground = "#d3c6aa"
background = "#1e2326"
cursor = "#e69875"
selection = "#4c3743"

[theme.colors.normal]
black = "#7a8478"
red = "#e67e80"
green = "#a7c080"
yellow = "#dbbc7f"
blue = "#7fbbb3"
magenta = "#d699b6"
cyan = "#83c092"
white = "#f2efdf"

[theme.colors.bright]
black = "#a6b0a0"
red = "#f85552"
green = "#8da101"
yellow = "#dfa000"
blue = "#3a94c5"
magenta = "#df69ba"
cyan = "#35a77c"
white = "#fffbef"

[theme.agents]
plan = "#a277ff"
build = "#EC5B2B"
